[build]
target = "xtensa-esp32s3-none-elf"
target-dir = "/Users/morteanualexandru/.cargo-target/player"

[unstable]
build-std = ["core"]

[target.xtensa-esp32s3-none-elf]
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "link-arg=-nostartfiles",
]